window.APP_DATA = {
  "exercises": [
    {
      "id": 1,
      "group": "Peito",
      "name": "Supino reto",
      "muscle": "Peitoral maior",
      "sets": 4,
      "reps": "8–12",
      "rest": 90,
      "tip": "Escápulas retraídas, pés firmes e descida controlada.",
      "avoid": "Não quique a barra no peito nem abra demais os cotovelos."
    },
    {
      "id": 2,
      "group": "Peito",
      "name": "Supino inclinado",
      "muscle": "Peitoral superior",
      "sets": 3,
      "reps": "8–12",
      "rest": 90,
      "tip": "Banco em inclinação moderada e movimento controlado.",
      "avoid": "Evite inclinação excessiva e perder contato das escápulas com o banco."
    },
    {
      "id": 3,
      "group": "Peito",
      "name": "Supino declinado",
      "muscle": "Peitoral inferior",
      "sets": 3,
      "reps": "10–12",
      "rest": 75,
      "tip": "Mantenha a barra alinhada à porção inferior do peito.",
      "avoid": "Evite descer a barra em direção ao pescoço."
    },
    {
      "id": 4,
      "group": "Peito",
      "name": "Crucifixo com halteres",
      "muscle": "Peitoral",
      "sets": 3,
      "reps": "12–15",
      "rest": 60,
      "tip": "Leve flexão dos cotovelos e arco amplo.",
      "avoid": "Não transforme o movimento em supino."
    },
    {
      "id": 5,
      "group": "Peito",
      "name": "Crossover alto",
      "muscle": "Peitoral inferior",
      "sets": 3,
      "reps": "12–15",
      "rest": 60,
      "tip": "Traga as mãos para baixo e à frente do corpo.",
      "avoid": "Não use impulso do tronco."
    },
    {
      "id": 6,
      "group": "Peito",
      "name": "Crossover médio",
      "muscle": "Peitoral",
      "sets": 3,
      "reps": "12–15",
      "rest": 60,
      "tip": "Cruze as mãos levemente à frente do peito.",
      "avoid": "Evite encurtar demais a amplitude."
    },
    {
      "id": 7,
      "group": "Peito",
      "name": "Crossover baixo",
      "muscle": "Peitoral superior",
      "sets": 3,
      "reps": "12–15",
      "rest": 60,
      "tip": "Puxe de baixo para cima em direção ao centro do peito.",
      "avoid": "Não arqueie a lombar."
    },
    {
      "id": 8,
      "group": "Peito",
      "name": "Peck deck",
      "muscle": "Peitoral",
      "sets": 3,
      "reps": "12–15",
      "rest": 60,
      "tip": "Costas apoiadas e contração máxima à frente.",
      "avoid": "Evite bater as placas da máquina."
    },
    {
      "id": 9,
      "group": "Peito",
      "name": "Flexão de braços",
      "muscle": "Peitoral/tríceps",
      "sets": 3,
      "reps": "10–20",
      "rest": 60,
      "tip": "Corpo alinhado e peito aproximando do chão.",
      "avoid": "Não deixe o quadril cair."
    },
    {
      "id": 10,
      "group": "Costas",
      "name": "Barra fixa",
      "muscle": "Dorsal",
      "sets": 4,
      "reps": "6–12",
      "rest": 90,
      "tip": "Suba sem balanço e controle a descida.",
      "avoid": "Evite chutar ou encurtar a amplitude."
    },
    {
      "id": 11,
      "group": "Costas",
      "name": "Puxada alta pronada",
      "muscle": "Dorsal",
      "sets": 3,
      "reps": "8–12",
      "rest": 75,
      "tip": "Puxe a barra até a parte superior do peito.",
      "avoid": "Não leve a barra atrás da nuca."
    },
    {
      "id": 12,
      "group": "Costas",
      "name": "Puxada neutra",
      "muscle": "Dorsal",
      "sets": 3,
      "reps": "10–12",
      "rest": 75,
      "tip": "Mantenha peito aberto e cotovelos para baixo.",
      "avoid": "Evite curvar excessivamente o tronco."
    },
    {
      "id": 13,
      "group": "Costas",
      "name": "Remada baixa",
      "muscle": "Dorsal/romboides",
      "sets": 3,
      "reps": "10–12",
      "rest": 75,
      "tip": "Finalize aproximando as escápulas.",
      "avoid": "Não balance o tronco."
    },
    {
      "id": 14,
      "group": "Costas",
      "name": "Remada curvada",
      "muscle": "Dorsal/romboides",
      "sets": 4,
      "reps": "8–12",
      "rest": 90,
      "tip": "Coluna neutra e barra próxima ao corpo.",
      "avoid": "Não arredonde a lombar."
    },
    {
      "id": 15,
      "group": "Costas",
      "name": "Remada unilateral",
      "muscle": "Dorsal",
      "sets": 3,
      "reps": "10–12",
      "rest": 75,
      "tip": "Puxe o cotovelo em direção ao quadril.",
      "avoid": "Evite girar o tronco."
    },
    {
      "id": 16,
      "group": "Costas",
      "name": "Remada cavalinho",
      "muscle": "Costas médias",
      "sets": 3,
      "reps": "8–12",
      "rest": 90,
      "tip": "Peito aberto e cotovelos acompanhando a linha do corpo.",
      "avoid": "Não hiperestenda a lombar."
    },
    {
      "id": 17,
      "group": "Costas",
      "name": "Pullover na polia",
      "muscle": "Dorsal",
      "sets": 3,
      "reps": "12–15",
      "rest": 60,
      "tip": "Braços quase estendidos e foco em puxar com as costas.",
      "avoid": "Não transforme em tríceps."
    },
    {
      "id": 18,
      "group": "Costas",
      "name": "Face pull",
      "muscle": "Deltoide posterior/romboides",
      "sets": 3,
      "reps": "12–15",
      "rest": 60,
      "tip": "Puxe em direção ao rosto com cotovelos altos.",
      "avoid": "Evite usar carga excessiva."
    },
    {
      "id": 19,
      "group": "Ombros",
      "name": "Desenvolvimento com halteres",
      "muscle": "Deltoides",
      "sets": 4,
      "reps": "8–12",
      "rest": 90,
      "tip": "Abdômen firme e halteres acima dos ombros.",
      "avoid": "Não arqueie excessivamente a lombar."
    },
    {
      "id": 20,
      "group": "Ombros",
      "name": "Desenvolvimento na máquina",
      "muscle": "Deltoides",
      "sets": 3,
      "reps": "10–12",
      "rest": 75,
      "tip": "Ajuste o banco para manter pegada na linha dos ombros.",
      "avoid": "Evite travar os cotovelos."
    },
    {
      "id": 21,
      "group": "Ombros",
      "name": "Elevação lateral",
      "muscle": "Deltoide lateral",
      "sets": 4,
      "reps": "12–15",
      "rest": 60,
      "tip": "Eleve até a linha dos ombros sem impulso.",
      "avoid": "Não encolha os ombros."
    },
    {
      "id": 22,
      "group": "Ombros",
      "name": "Elevação frontal",
      "muscle": "Deltoide anterior",
      "sets": 3,
      "reps": "10–15",
      "rest": 60,
      "tip": "Eleve controladamente até a altura dos ombros.",
      "avoid": "Evite balançar o tronco."
    },
    {
      "id": 23,
      "group": "Ombros",
      "name": "Crucifixo inverso",
      "muscle": "Deltoide posterior",
      "sets": 3,
      "reps": "12–15",
      "rest": 60,
      "tip": "Abra os braços mantendo leve flexão dos cotovelos.",
      "avoid": "Não use carga que comprometa a postura."
    },
    {
      "id": 24,
      "group": "Ombros",
      "name": "Face pull",
      "muscle": "Deltoide posterior",
      "sets": 3,
      "reps": "12–15",
      "rest": 60,
      "tip": "Puxe a corda em direção ao rosto.",
      "avoid": "Não abaixe os cotovelos durante a puxada."
    },
    {
      "id": 25,
      "group": "Ombros",
      "name": "Remada alta",
      "muscle": "Deltoides/trapézio",
      "sets": 3,
      "reps": "10–12",
      "rest": 60,
      "tip": "Suba até altura confortável, sem forçar a articulação.",
      "avoid": "Evite elevar demais os cotovelos se houver desconforto."
    },
    {
      "id": 26,
      "group": "Ombros",
      "name": "Encolhimento",
      "muscle": "Trapézio",
      "sets": 3,
      "reps": "10–15",
      "rest": 60,
      "tip": "Eleve os ombros verticalmente e segure no topo.",
      "avoid": "Não faça círculos com os ombros."
    },
    {
      "id": 27,
      "group": "Bíceps",
      "name": "Rosca direta barra",
      "muscle": "Bíceps",
      "sets": 4,
      "reps": "8–12",
      "rest": 60,
      "tip": "Cotovelos fixos e punhos neutros.",
      "avoid": "Não balance o tronco."
    },
    {
      "id": 28,
      "group": "Bíceps",
      "name": "Rosca alternada",
      "muscle": "Bíceps",
      "sets": 3,
      "reps": "10–12",
      "rest": 60,
      "tip": "Gire a palma para cima durante a subida.",
      "avoid": "Evite deslocar o cotovelo para frente."
    },
    {
      "id": 29,
      "group": "Bíceps",
      "name": "Rosca martelo",
      "muscle": "Braquial/bíceps",
      "sets": 3,
      "reps": "10–12",
      "rest": 60,
      "tip": "Pegada neutra e cotovelos próximos ao corpo.",
      "avoid": "Não use impulso."
    },
    {
      "id": 30,
      "group": "Bíceps",
      "name": "Rosca Scott",
      "muscle": "Bíceps",
      "sets": 3,
      "reps": "10–12",
      "rest": 60,
      "tip": "Braços apoiados e descida controlada.",
      "avoid": "Não hiperestenda o cotovelo no final."
    },
    {
      "id": 31,
      "group": "Bíceps",
      "name": "Rosca concentrada",
      "muscle": "Bíceps",
      "sets": 3,
      "reps": "10–15",
      "rest": 60,
      "tip": "Apoie o cotovelo e concentre a contração.",
      "avoid": "Não mova o ombro."
    },
    {
      "id": 32,
      "group": "Bíceps",
      "name": "Rosca na polia",
      "muscle": "Bíceps",
      "sets": 3,
      "reps": "12–15",
      "rest": 60,
      "tip": "Mantenha tensão contínua durante todo o movimento.",
      "avoid": "Não deixe o peso puxar os ombros para frente."
    },
    {
      "id": 33,
      "group": "Bíceps",
      "name": "Rosca inclinada",
      "muscle": "Bíceps",
      "sets": 3,
      "reps": "10–12",
      "rest": 60,
      "tip": "Braços atrás da linha do tronco e movimento completo.",
      "avoid": "Não suba os cotovelos."
    },
    {
      "id": 34,
      "group": "Tríceps",
      "name": "Tríceps corda",
      "muscle": "Tríceps",
      "sets": 4,
      "reps": "10–15",
      "rest": 60,
      "tip": "Cotovelos junto ao corpo e extensão completa.",
      "avoid": "Não balance o tronco."
    },
    {
      "id": 35,
      "group": "Tríceps",
      "name": "Tríceps barra",
      "muscle": "Tríceps",
      "sets": 3,
      "reps": "10–12",
      "rest": 60,
      "tip": "Antebraços se movem; braços ficam estáveis.",
      "avoid": "Não abra os cotovelos."
    },
    {
      "id": 36,
      "group": "Tríceps",
      "name": "Tríceps testa",
      "muscle": "Tríceps",
      "sets": 3,
      "reps": "8–12",
      "rest": 75,
      "tip": "Cotovelos apontados para cima e descida controlada.",
      "avoid": "Não deixe os cotovelos abrirem."
    },
    {
      "id": 37,
      "group": "Tríceps",
      "name": "Tríceps francês",
      "muscle": "Tríceps",
      "sets": 3,
      "reps": "10–12",
      "rest": 60,
      "tip": "Mantenha abdômen firme e cotovelos próximos.",
      "avoid": "Não arqueie a lombar."
    },
    {
      "id": 38,
      "group": "Tríceps",
      "name": "Tríceps unilateral polia",
      "muscle": "Tríceps",
      "sets": 3,
      "reps": "12–15",
      "rest": 60,
      "tip": "Estenda o braço completamente sem girar o tronco.",
      "avoid": "Não mova o ombro."
    },
    {
      "id": 39,
      "group": "Tríceps",
      "name": "Mergulho em banco",
      "muscle": "Tríceps",
      "sets": 3,
      "reps": "10–15",
      "rest": 60,
      "tip": "Desça até amplitude confortável com ombros estáveis.",
      "avoid": "Evite descer excessivamente."
    },
    {
      "id": 40,
      "group": "Tríceps",
      "name": "Paralelas",
      "muscle": "Tríceps/peitoral",
      "sets": 3,
      "reps": "6–12",
      "rest": 90,
      "tip": "Tronco relativamente vertical para enfatizar tríceps.",
      "avoid": "Não mergulhe além da mobilidade do ombro."
    },
    {
      "id": 41,
      "group": "Pernas",
      "name": "Agachamento livre",
      "muscle": "Quadríceps/glúteos",
      "sets": 4,
      "reps": "6–10",
      "rest": 120,
      "tip": "Pés firmes, coluna neutra e joelhos alinhados.",
      "avoid": "Não deixe os joelhos colapsarem para dentro."
    },
    {
      "id": 42,
      "group": "Pernas",
      "name": "Leg press 45°",
      "muscle": "Quadríceps/glúteos",
      "sets": 4,
      "reps": "10–15",
      "rest": 90,
      "tip": "Lombar apoiada e amplitude confortável.",
      "avoid": "Não trave os joelhos."
    },
    {
      "id": 43,
      "group": "Pernas",
      "name": "Cadeira extensora",
      "muscle": "Quadríceps",
      "sets": 3,
      "reps": "12–15",
      "rest": 60,
      "tip": "Estenda os joelhos controladamente e segure no topo.",
      "avoid": "Não use impulso."
    },
    {
      "id": 44,
      "group": "Pernas",
      "name": "Mesa flexora",
      "muscle": "Posterior de coxa",
      "sets": 3,
      "reps": "10–15",
      "rest": 60,
      "tip": "Mantenha quadril apoiado e flexione os joelhos.",
      "avoid": "Não levante o quadril."
    },
    {
      "id": 45,
      "group": "Pernas",
      "name": "Cadeira flexora",
      "muscle": "Posterior de coxa",
      "sets": 3,
      "reps": "10–15",
      "rest": 60,
      "tip": "Ajuste o encosto e mantenha movimento controlado.",
      "avoid": "Não solte o peso na volta."
    },
    {
      "id": 46,
      "group": "Pernas",
      "name": "Stiff",
      "muscle": "Posterior/glúteos",
      "sets": 4,
      "reps": "8–12",
      "rest": 90,
      "tip": "Quadril para trás e coluna neutra.",
      "avoid": "Não arredonde a lombar."
    },
    {
      "id": 47,
      "group": "Pernas",
      "name": "Afundo",
      "muscle": "Quadríceps/glúteos",
      "sets": 3,
      "reps": "8–12 por perna",
      "rest": 75,
      "tip": "Passo estável e tronco controlado.",
      "avoid": "Não deixe o joelho da frente colapsar para dentro."
    },
    {
      "id": 48,
      "group": "Pernas",
      "name": "Agachamento búlgaro",
      "muscle": "Quadríceps/glúteos",
      "sets": 3,
      "reps": "8–12 por perna",
      "rest": 75,
      "tip": "Desça verticalmente com base estável.",
      "avoid": "Não perca o equilíbrio pela pressa."
    },
    {
      "id": 49,
      "group": "Pernas",
      "name": "Elevação pélvica",
      "muscle": "Glúteos",
      "sets": 4,
      "reps": "8–12",
      "rest": 90,
      "tip": "Queixo levemente recolhido e contração no topo.",
      "avoid": "Não hiperestenda a lombar."
    },
    {
      "id": 50,
      "group": "Pernas",
      "name": "Panturrilha em pé",
      "muscle": "Panturrilhas",
      "sets": 4,
      "reps": "12–20",
      "rest": 45,
      "tip": "Use amplitude completa, subindo e descendo devagar.",
      "avoid": "Não faça repetições curtas e rápidas."
    },
    {
      "id": 51,
      "group": "Pernas",
      "name": "Panturrilha sentada",
      "muscle": "Sóleo",
      "sets": 3,
      "reps": "15–20",
      "rest": 45,
      "tip": "Eleve os calcanhares e controle a descida.",
      "avoid": "Não quique o peso."
    },
    {
      "id": 52,
      "group": "Abdômen",
      "name": "Crunch tradicional",
      "muscle": "Reto abdominal",
      "sets": 3,
      "reps": "15–20",
      "rest": 45,
      "tip": "Aproxime costelas da pelve sem puxar o pescoço.",
      "avoid": "Não use as mãos para puxar a cabeça."
    },
    {
      "id": 53,
      "group": "Abdômen",
      "name": "Crunch na polia",
      "muscle": "Reto abdominal",
      "sets": 3,
      "reps": "12–15",
      "rest": 60,
      "tip": "Flexione o tronco usando o abdômen.",
      "avoid": "Não puxe apenas com os braços."
    },
    {
      "id": 54,
      "group": "Abdômen",
      "name": "Prancha frontal",
      "muscle": "Core",
      "sets": 3,
      "reps": "30–60 s",
      "rest": 45,
      "tip": "Corpo alinhado e abdômen contraído.",
      "avoid": "Não deixe o quadril cair."
    },
    {
      "id": 55,
      "group": "Abdômen",
      "name": "Prancha lateral",
      "muscle": "Oblíquos/core",
      "sets": 3,
      "reps": "20–45 s por lado",
      "rest": 45,
      "tip": "Mantenha quadril elevado e corpo alinhado.",
      "avoid": "Não deixe o ombro afundar."
    },
    {
      "id": 56,
      "group": "Abdômen",
      "name": "Elevação de pernas",
      "muscle": "Abdômen inferior",
      "sets": 3,
      "reps": "10–15",
      "rest": 45,
      "tip": "Controle a descida e mantenha lombar estável.",
      "avoid": "Não balance as pernas."
    },
    {
      "id": 57,
      "group": "Abdômen",
      "name": "Abdominal bicicleta",
      "muscle": "Oblíquos",
      "sets": 3,
      "reps": "16–24 total",
      "rest": 45,
      "tip": "Gire o tronco aproximando ombro e joelho opostos.",
      "avoid": "Não puxe o pescoço."
    },
    {
      "id": 58,
      "group": "Abdômen",
      "name": "Abdominal oblíquo",
      "muscle": "Oblíquos",
      "sets": 3,
      "reps": "12–20 por lado",
      "rest": 45,
      "tip": "Faça flexão lateral controlada.",
      "avoid": "Não transforme em rotação brusca."
    },
    {
      "id": 59,
      "group": "Abdômen",
      "name": "Dead bug",
      "muscle": "Core profundo",
      "sets": 3,
      "reps": "8–12 por lado",
      "rest": 45,
      "tip": "Mantenha a lombar em contato com o solo.",
      "avoid": "Não acelere o movimento."
    },
    {
      "id": 60,
      "group": "Alongamento",
      "name": "Pescoço lateral",
      "muscle": "Cervical",
      "sets": 2,
      "reps": "20–30 s por lado",
      "rest": 20,
      "tip": "Incline suavemente a cabeça para o lado.",
      "avoid": "Não force com a mão."
    },
    {
      "id": 61,
      "group": "Alongamento",
      "name": "Trapézio",
      "muscle": "Trapézio superior",
      "sets": 2,
      "reps": "20–30 s por lado",
      "rest": 20,
      "tip": "Incline a cabeça diagonalmente e mantenha ombro relaxado.",
      "avoid": "Não faça movimentos bruscos."
    },
    {
      "id": 62,
      "group": "Alongamento",
      "name": "Peitoral na parede",
      "muscle": "Peitoral",
      "sets": 2,
      "reps": "20–30 s por lado",
      "rest": 20,
      "tip": "Apoie o braço e gire suavemente o tronco.",
      "avoid": "Não force o ombro."
    },
    {
      "id": 63,
      "group": "Alongamento",
      "name": "Ombro cruzado",
      "muscle": "Deltoide posterior",
      "sets": 2,
      "reps": "20–30 s por lado",
      "rest": 20,
      "tip": "Traga o braço à frente do peito e sustente.",
      "avoid": "Não pressione sobre a articulação do cotovelo."
    },
    {
      "id": 64,
      "group": "Alongamento",
      "name": "Tríceps acima da cabeça",
      "muscle": "Tríceps/ombro",
      "sets": 2,
      "reps": "20–30 s por lado",
      "rest": 20,
      "tip": "Flexione o cotovelo e sustente suavemente.",
      "avoid": "Não force a cervical."
    },
    {
      "id": 65,
      "group": "Alongamento",
      "name": "Posterior de coxa",
      "muscle": "Isquiotibiais",
      "sets": 2,
      "reps": "20–30 s por lado",
      "rest": 20,
      "tip": "Incline o tronco mantendo a coluna longa.",
      "avoid": "Não arredonde excessivamente a lombar."
    },
    {
      "id": 66,
      "group": "Alongamento",
      "name": "Quadríceps em pé",
      "muscle": "Quadríceps",
      "sets": 2,
      "reps": "20–30 s por lado",
      "rest": 20,
      "tip": "Aproxime o calcanhar do glúteo mantendo joelhos juntos.",
      "avoid": "Não arqueie a lombar."
    },
    {
      "id": 67,
      "group": "Alongamento",
      "name": "Panturrilha na parede",
      "muscle": "Panturrilha",
      "sets": 2,
      "reps": "20–30 s por lado",
      "rest": 20,
      "tip": "Calcanhar no chão e joelho estendido.",
      "avoid": "Não gire o pé para fora."
    },
    {
      "id": 68,
      "group": "Alongamento",
      "name": "Glúteo deitado",
      "muscle": "Glúteos/piriforme",
      "sets": 2,
      "reps": "20–30 s por lado",
      "rest": 20,
      "tip": "Cruze a perna e aproxime suavemente.",
      "avoid": "Não force o joelho."
    },
    {
      "id": 69,
      "group": "Alongamento",
      "name": "Flexor do quadril",
      "muscle": "Iliopsoas",
      "sets": 2,
      "reps": "20–30 s por lado",
      "rest": 20,
      "tip": "Leve o quadril à frente com tronco ereto.",
      "avoid": "Não hiperestenda a lombar."
    }
  ],
  "plans": {
    "Treino A — Peito + Tríceps": [
      "Supino reto",
      "Supino inclinado",
      "Crucifixo com halteres",
      "Crossover médio",
      "Tríceps corda",
      "Tríceps testa",
      "Tríceps francês"
    ],
    "Treino B — Costas + Bíceps": [
      "Barra fixa",
      "Puxada alta pronada",
      "Remada baixa",
      "Remada unilateral",
      "Pullover na polia",
      "Rosca direta barra",
      "Rosca martelo",
      "Rosca Scott"
    ],
    "Treino C — Pernas": [
      "Agachamento livre",
      "Leg press 45°",
      "Cadeira extensora",
      "Mesa flexora",
      "Stiff",
      "Elevação pélvica",
      "Panturrilha em pé"
    ],
    "Treino D — Ombros + Core": [
      "Desenvolvimento com halteres",
      "Elevação lateral",
      "Crucifixo inverso",
      "Face pull",
      "Prancha frontal",
      "Prancha lateral",
      "Dead bug"
    ]
  }
};